// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/note/note.proto

package go_micro_srv_note

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Note
type Note struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Note) Reset()         { *m = Note{} }
func (m *Note) String() string { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()    {}
func (*Note) Descriptor() ([]byte, []int) {
	return fileDescriptor_note_649506335fcfcf07, []int{0}
}
func (m *Note) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Note.Unmarshal(m, b)
}
func (m *Note) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Note.Marshal(b, m, deterministic)
}
func (dst *Note) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Note.Merge(dst, src)
}
func (m *Note) XXX_Size() int {
	return xxx_messageInfo_Note.Size(m)
}
func (m *Note) XXX_DiscardUnknown() {
	xxx_messageInfo_Note.DiscardUnknown(m)
}

var xxx_messageInfo_Note proto.InternalMessageInfo

func (m *Note) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Note) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// response
type Response struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_note_649506335fcfcf07, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Response) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Response) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*Note)(nil), "go.micro.srv.note.Note")
	proto.RegisterType((*Response)(nil), "go.micro.srv.note.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for NoteService service

type NoteServiceClient interface {
	// 新建笔记
	CreateNote(ctx context.Context, in *Note, opts ...client.CallOption) (*Response, error)
}

type noteServiceClient struct {
	c           client.Client
	serviceName string
}

func NewNoteServiceClient(serviceName string, c client.Client) NoteServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.note"
	}
	return &noteServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *noteServiceClient) CreateNote(ctx context.Context, in *Note, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "NoteService.CreateNote", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NoteService service

type NoteServiceHandler interface {
	// 新建笔记
	CreateNote(context.Context, *Note, *Response) error
}

func RegisterNoteServiceHandler(s server.Server, hdlr NoteServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&NoteService{hdlr}, opts...))
}

type NoteService struct {
	NoteServiceHandler
}

func (h *NoteService) CreateNote(ctx context.Context, in *Note, out *Response) error {
	return h.NoteServiceHandler.CreateNote(ctx, in, out)
}

func init() { proto.RegisterFile("proto/note/note.proto", fileDescriptor_note_649506335fcfcf07) }

var fileDescriptor_note_649506335fcfcf07 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x3f, 0xcb, 0xc2, 0x30,
	0x10, 0xc6, 0xdf, 0xf6, 0x2d, 0xfe, 0xb9, 0x82, 0x60, 0x40, 0x0c, 0x3a, 0x28, 0x9d, 0x9c, 0xa2,
	0xe8, 0x47, 0xd0, 0xd9, 0xa1, 0x75, 0x17, 0x4d, 0x0f, 0xc9, 0xd0, 0x5c, 0x49, 0x63, 0x3f, 0xbf,
	0xe4, 0x4a, 0x5d, 0x74, 0x71, 0x09, 0xdc, 0xf3, 0xfb, 0x1d, 0x3c, 0x39, 0x98, 0xd5, 0x8e, 0x3c,
	0x6d, 0x2d, 0x79, 0xe4, 0x47, 0xf1, 0x2c, 0xa6, 0x0f, 0x52, 0x95, 0xd1, 0x8e, 0x54, 0xe3, 0x5a,
	0x15, 0x40, 0xb6, 0x83, 0xe4, 0x4c, 0x1e, 0xc5, 0x04, 0x62, 0x53, 0xca, 0x68, 0x1d, 0x6d, 0xc6,
	0x79, 0x6c, 0x4a, 0x21, 0x61, 0xa8, 0xc9, 0x7a, 0xb4, 0x5e, 0xc6, 0x1c, 0xf6, 0x63, 0xd6, 0xc2,
	0x28, 0xc7, 0xa6, 0x26, 0xdb, 0xfc, 0xb0, 0x25, 0x56, 0x90, 0x6a, 0x87, 0x37, 0x8f, 0x57, 0x6f,
	0x2a, 0x94, 0xff, 0x4c, 0xa1, 0x8b, 0x2e, 0xa6, 0xc2, 0x20, 0x3c, 0xeb, 0xf2, 0x2d, 0x24, 0x9d,
	0xd0, 0x45, 0x41, 0xd8, 0x17, 0x90, 0x86, 0xa6, 0x05, 0xba, 0xd6, 0x68, 0x14, 0x27, 0x80, 0x23,
	0x6f, 0x73, 0xfd, 0xb9, 0xfa, 0xf8, 0x9a, 0x0a, 0x60, 0xb1, 0xfc, 0x02, 0xfa, 0xfa, 0xd9, 0xdf,
	0x7d, 0xc0, 0x87, 0x39, 0xbc, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x87, 0x79, 0xee, 0x31, 0x01,
	0x00, 0x00,
}
